COLOR_TRACK_DEFAULT="black"
COLOR_CUT="red"
COLOR_ENGRAVE="blue"


GRID_SIZE=5
TRACK_SIZE=4

LED_SIZE=3
LED_MARGIN=.5
LED_COLOR="lime"
CLOSED_LED_COLOR=LED_COLOR
THROWN_LED_COLOR="yellow"

SWITH_HOLE_SIZE=6
SWITH_HOLE_MARGIN_SIZE=12
SWITH_SIZE=(10,15)
SWITH_SIZE_H=(15,10)